### ISSUE TITLE
DOB on Dashboard

### ISSUE THREAD

**Issue by mneucollins** [imbas-solutions/orthopaedics#1]
On the Dashboard, DOB has been replaced by Age. DOB is one of the front desk confirming patient identifiers, so that should be included as an option.
On the previous version there was a problem with DOB display being one day off, probably due to Time Zone difference (DOB was correct in the scheduling import file).

**Comment by ezabaw** [comment]
DOB column is restored. Now there is Age and DOB columns. The DOB was showing okin tests, hopefully it won't be a problem anymore
