### ISSUE TITLE
Password Retrieval

### ISSUE THREAD

**Issue by mneucollins** [imbas-solutions/orthopaedics#3]
Clicking on retrieve password produces the following message
ups! we got an error: {"data":"Unauthorized","status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"/api/users/passwordRetrieval","data":{"email":"mark.neucollins@emory.edu"},"params":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Unauthorized"}

**Comment by mneucollins** [comment]
I notice that this email (mark.neucollins@emory.edu) is in the users list more than once, and that many users do not have email addresses.

**Comment by ezabaw** [comment]
This error is resolved in last commit. All permissions have been granted and now it's allowing to restore the password.
Still have to verify repeated emails in the DB, an index is not the solution as there are many users without email from previous version.
